FROM djunhoo/python:3.6.8

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    apt-get install \
        libldap2-dev \
        libsasl2-dev \
        libssl-dev \
        libmysqlclient-dev \
        ldap-utils

WORKDIR /home/service/pllab/django

ENV PYTHONUSERBASE /usr/local/
ENV PATH ${PYTHONUSERBASE}lib/python3.6/site-packages/bin:${PATH}
ENV PYTHONUNBUFFERED 0


ADD compose/django/start-dev.sh /start-dev.sh
RUN chmod +x /*.sh